### ISSUE TITLE
Terraform0.13に対応する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/terraform-aws-vpc#10]
## Doneの定義
- Terraform0.13に対応していること

## 補足
Terraformのバージョンが`0.12.24`で固定されており、moduleを利用する側が異なるバージョンを指定していると利用することができなかったので対応する

**Comment by kobayashi-m42** [comment]
@keitakn Terraform Registoryに公開するところまで対応すると、ポイントは2か3かな？

**Comment by keitakn** [comment]
@kobayashi-m42 3でいいと思う🐱！

今回メジャーバージョンアップになるから、タグも `v2.0.0` でリリースして良いと思う！
